- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start Service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
    - name: Start mariadb Service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
