---
- name: Database server setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      yum:
        name: mariadb-server
        state: present

    - name : Install python3-mysql
      yum:
        name: python3-PyMySQL
        state: present
    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: bobdata
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user with name 'bob' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
