all:
  hosts:
    web01:
      ansible_host: "{{ web01_ip }}"
    web02:
      ansible_host: "{{ web02_ip }}"
    web03:
      ansible_host: "{{ web03_ip }}"
    db01:
      ansible_host: "{{ db01_ip }}"
  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: clientkey.pem