---
- name: Print Facts
  hosts: all
    #gather_facts: False
  tasks:
    - name: Print os name
      debug:
        var: ansible_distribution
    - name: Print selinux mode
      debug:
        var: ansible_selinux.mode
    - name: Print Ram memory
      debug:
        var: ansible_memory_mb.real.free
    - name: Print Processor
      debug:
        var: ansible_processor[2]